services:
  backend:
    container_name: crud-backend-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      POSTGRES_DB: go_app_dev
      POSTGRES_HOST: crud-backend-postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      JWT_SECRET_KEY: ObL89O3nOSSEj6tbdHako0cXtPErzBUfq8l8o/3KD9g=INSECURE
      API_SECRET_KEY: cJGZ8L1sDcPezjOy1zacPJZxzZxrPObm2Ggs1U0V+fE=INSECURE
      REDIS_HOST: redis
    networks:
      - app_network

  db:
    image: postgres:14.1
    container_name: crud-backend-postgres
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=go_app_dev
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
    networks:
      - app_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: crud-backend-redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
