name: Backend

on:
  workflow_dispatch:  # Enables the manual trigger option
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '!backend/**/*.md'  # Exclude .md files within 'backend'
      - '!backend/CODEOWNERS'
      - '!backend/Makefile'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '!backend/**/*.md'
      - '!backend/CODEOWNERS'
      - '!backend/Makefile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: cd backend && go build -v ./...

    - name: Test
      run: cd backend && go test -v ./... -race -cover
